### ISSUE TITLE
the code is a bit wrong?

### ISSUE THREAD

**Issue by huhusmang** [lupantech/chameleon-llm#3]
The `update_modules` function in run_scienceqa/model.py, `default_modules = eval(["solution_generator", "answer_generator"])`, here executes eval() on a list

**Comment by huhusmang** [comment]
``` python
def score_string_similarity(str1, str2):
    if str1 == str2:
        return 2.0
    if " " in str1 or " " in str2:
        str1_split = str1.split(" ")
        str2_split = str2.split(" ")
        overlap = list(set(str1_split) & set(str2_split))
        return len(overlap) / max(len(str1_split), len(str2_split))
    else:
        if str1 == str2:
            return 1.0
        else:
            return 0.0
```
In Step 1, the case where two strings are exactly the same has already been handled, so in Step 3, the condition "if str1 == str2" will never be satisfied, and it is actually unnecessary

**Comment by lupantech** [comment]
> 
Hi, thank you so much for pointing it out! I have fixed this issue.

**Comment by lupantech** [comment]
> The `update_modules` function in run_scienceqa/model.py, `default_modules = eval(["solution_generator", "answer_generator"])`, here executes eval() on a list

Hi, thank you so much for pointing it out! I have fixed this issue.

**Comment by lupantech** [comment]
> ```python
> def score_string_similarity(str1, str2):
>     if str1 == str2:
>         return 2.0
>     if " " in str1 or " " in str2:
>         str1_split = str1.split(" ")
>         str2_split = str2.split(" ")
>         overlap = list(set(str1_split) & set(str2_split))
>         return len(overlap) / max(len(str1_split), len(str2_split))
>     else:
>         if str1 == str2:
>             return 1.0
>         else:
>             return 0.0
> ```

Hi, I checked the code and didn't find the code snippet you mentioned. Would you mind providing me with more specific information? I am happy to fix it if there are any bugs. Thanks!

Below is the `update_modules` function from the current code:

```
    def update_modules(self, _modules):
        # default modules
        default_modules = ["solution_generator", "answer_generator"]
        
        try:
            modules = eval(_modules.lower().strip())
            assert modules[-2:] == default_modules
        except:
            modules = default_modules

        return modules
```

**Comment by huhusmang** [comment]
Of course, the `score_string_similarity()`  function is here: utilities.py. And by the way, how are you going to implement live calling modules?

**Comment by lupantech** [comment]
Thanks. Apologies for the wrong quote in the previous reply.

For now, most modules are implemented using live calling. However, the text_detector and image_captioner are off-the-shelf, i.e., the responses are prepared in advance for simpler development and quicker inference.

We will add the live calling implementations soon, which is on our to-do list.

**Comment by huhusmang** [comment]
Thanks, looking forward to it !
